apiVersion: v1
kind: Service
metadata:
  labels:
    run: first-service
  name: first-service
  namespace: default
spec:
type: NodePort
ports:
  - name: p1
    port: 80
    targetPort: 80
    nodePort: 32234
selector:
    run: first-pod
